### ISSUE TITLE
Docker Compose YAML ?

### ISSUE THREAD

**Issue by Domoel** [SchildiChat/website#21]
Hi,

I want to build the web application with docker. Are there some docker compose instruction available?

**Comment by Domoel** [comment]
Due to the fact that I wasn't able to find one in the internet I just created a docker compose file by myself. So if someone is looking for it, here you go:

```
services:
  schildichat:
    image: paritytech/schildichat-web:latest
    container_name: schildichat
    restart: unless-stopped
    networks:
      - frontend
    ports:
     - 1337:80
    volumes:
     - ./config.json:/app/config.json

networks:
  frontend:
    external: true
    name: schildichat
```

Please ensure that the following prerequisits are met:
- Optional: Change the volume path in accordance with you directory from `./config.json:/app/config.json` (relative) to something like `/docker/path/config.json:/app/config.json`
- Create a docker network with the name `schildichat`.
- put a configured `config.json` in the directory path defined.

Example for `config.json`:

```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "YOURHOMESERVERURL", # Mustt be changed
            "server_name": "NAMEOFYOURHOMESERVER" # Change to your likings
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
    "disable_custom_urls": false, # Customize to your liking
    "disable_guests": true, # Customize to your liking
    "disable_login_language_selector": true, # Customize to your liking
    "disable_3pid_login": false, # Customize to your liking
    "brand": "NAMEOFYOURHOMESERVER", # Change to your likings
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "default_country_code": "DE",  Cchange to your likings
    "show_labs_settings": true, # Change to your likings
    "features": {},
    "default_federate": true,
    "default_theme": "dark",
    "room_directory": {
        "servers": ["matrix.org"]
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    },
    "setting_defaults": {
        "breadcrumbs": true
    },
    "jitsi": {
        "preferred_domain": "meet.jit.si"
    },
    "element_call": {
        "url": "https://call.element.io",
        "participant_limit": 8,
        "brand": "NAMEOFYOURHOMESERVER" # Change to your likings 
    },
    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
}
```
